import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/dist/client/router";
import { IChildren } from "../interfaces/interfaces";
import React from "react";
import { Navbar, Nav, Container } from "react-bootstrap";

export const General = ({ children }: IChildren) => {
  const router = useRouter();

  return (
    <section className={styles.container}>
      <Head>
        <title>Страны</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
        <Container>
          
          <Navbar.Toggle aria-controls="responsive-navbar-nav" />
          <Navbar.Collapse id="responsive-navbar-nav">
            <Nav className="me-auto">
              <Nav.Link href={"/"}><Navbar.Brand>Back-end Task</Navbar.Brand></Nav.Link>
              <Nav.Link href={"/taskOne"}>Задание 1</Nav.Link>
              <Nav.Link href={"/taskTwo"}>Задание 2</Nav.Link>
              <Nav.Link href={"/taskThree"}>Задание 3</Nav.Link>
              <Nav.Link href={"/taskFoo"}>Задание 4</Nav.Link>
              <Nav.Link href={"/taskFive"}>Задание 5</Nav.Link>
              <Nav.Link href={"/taskSix"}>Задание 6</Nav.Link>
              <Nav.Link href={"/taskSeven"}>Задание 7</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <section className={styles.main}>
      {children}
      </section>
    </section>
  );
};
